Repository g1eny0ung/hugo-theme-dream, pull requests merged in 2024-09, with the labels that each got.

#309 feat: add `valineConfig` param
  docs/pages/CHANGELOG.md
  docs/pages/params-configurations.mdx
  hugo.example.toml
  layouts/_default/single.html
Labels: enhancement

#310 feat: support Waline comment system
  docs/pages/CHANGELOG.md
  docs/pages/params-configurations.mdx
  docs/pages/social-comments.mdx
  hugo.example.toml
  layouts/_default/single.html
  layouts/partials/commentSystemHeads.html
  layouts/partials/commentSystems.html
Labels: feature

#320 feat: add reorderShares param
  docs/pages/CHANGELOG.md
  docs/pages/params-configurations.mdx
  hugo.example.toml
  layouts/partials/nav.html
  layouts/partials/share.html
Labels: enhancement

#323 Tweak English translations for `minuteRead` and `updateAt`
  i18n/en.toml
Labels: bugfix
