Repository g1eny0ung/hugo-theme-dream, pull requests merged in 2024-08, with the labels that each got.

#296 feat: flexible nav items
  docs/pages/CHANGELOG.md
  docs/pages/_meta.json
  docs/pages/custom-nav-items.mdx
  docs/pages/params-configurations.mdx
  docs/pages/social-links.mdx
  hugo.example.toml
  layouts/partials/nav.html
  layouts/partials/navCustomItems.html
  layouts/partials/navMobileMenu.html
  layouts/partials/navRightMobile.html
  layouts/partials/navVRTTaxonomies.html
  layouts/partials/renderMobileNavItem.html
  layouts/partials/renderNavItem.html
Labels: feature

#299 feat: Zen mode
  docs/pages/_meta.json
  docs/pages/index.mdx
  docs/pages/params-configurations.mdx
  docs/pages/zen-mode.mdx
  docs/public/images/zen-mode.png
  docs/theme.config.jsx
  hugo.example.toml
  layouts/_default/baseof.html
  layouts/_default/term.html
  layouts/_default/terms.html
  layouts/_default/zen-summary.html
  layouts/index.html
  layouts/partials/nav.html
  layouts/partials/scripts.html
  layouts/partials/socials.html
  layouts/partials/zen-back.html
  layouts/section/search.html
  static/css/output.css
Labels: feature, v3.5

#301 feat: add `noDefaultSummaryCover` param
  docs/pages/params-configurations.mdx
  docs/pages/summary-images.mdx
  hugo.example.toml
  layouts/_default/summary.html
  layouts/_default/zen-summary.html
Labels: feature

#303 Enhance and Complete Japanese Translations
  i18n/ja.toml
Labels: enhancement, i18n

#305 refactor: supplement meta tags for SEO
  layouts/partials/head.html
Labels: enhancement

#306 fix: usage of schema template
  docs/pages/CHANGELOG.md
  layouts/_default/single.html
  layouts/partials/author.html
  layouts/partials/head.html
Labels: bugfix

#307 feat: add mermaid support
  docs/pages/post-page.mdx
  layouts/_default/_markup/render-codeblock-mermaid.html
  layouts/_default/baseof.html
Labels: feature

#308 feat: add alerts support
  docs/pages/post-page.mdx
  i18n/en.toml
  i18n/zh.toml
  layouts/_default/_markup/render-blockquote.html
  layouts/_default/single.html
  layouts/partials/footerRight.html
  src/input.css
  static/css/output.css
  tailwind.config.js
Labels: feature
