Repository g1eny0ung/hugo-theme-dream, pull requests merged in 2025-01, with the labels that each got.

#346 feat: open external links in a new window
  layouts/_default/_markup/render-link.html
Labels: enhancement

#350 feat: add MathJax support
  docs/pages/CHANGELOG.md
  docs/pages/post-page.mdx
  layouts/_default/_markup/render-codeblock-math.html
  layouts/_default/baseof.html
  layouts/partials/mathjax.html
Labels: feature

#354 feat: whether to remove author display
  assets/css/output.css
  docs/pages/CHANGELOG.md
  docs/pages/post-page.mdx
  layouts/_default/single.html
  layouts/_default/summary.html
Labels: enhancement

#356 chore: prioritize page descriptions
  docs/pages/CHANGELOG.md
  layouts/_default/summary.html
  layouts/partials/head.html
  layouts/section/search.html
Labels: enhancement

#361 Should use title for posts then fallback to "archives"
  layouts/section/posts.html
Labels: bugfix
